.TH "UILudo" 3 "Ludo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UILudo \- Represents the main window for the Ludo game UI\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <UILudo\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUILudo\fP (QWidget *parent=nullptr)"
.br
.RI "Constructs a new \fBUILudo\fP object\&. "
.ti -1c
.RI "\fB~UILudo\fP ()"
.br
.RI "Destroys the \fBUILudo\fP object\&. "
.ti -1c
.RI "void \fBInitializeBoard\fP ()"
.br
.RI "Initializes the game board\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents the main window for the Ludo game UI\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UILudo::UILudo (QWidget * parent = \fRnullptr\fP)"

.PP
Constructs a new \fBUILudo\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIparent\fP The parent widget\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Ludo from the source code\&.
